---
namespace: middleware_automation
name: jws
version: "1.2.3"
readme: README.md
authors:
  - George Zaronikas <gzaronik@redhat.com>
  - Romain Pelisse <belaran@redhat.com>
  - Harsha Cherukuri <hcheruku@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
  - Coty Sutherland <csutherl@redhat.com>
description: This collection contains the ansible playbook to setup JWS.
license_file: "LICENSE"
tags: [java, tomcat, server, apache, jws, modcluster, infrastructure, linux]
dependencies:
  middleware_automation.redhat_csp_download: '>=1.2.1'
  community.general: ">=5.6.0"
repository: https://github.com/ansible-middleware/jws
documentation: https://ansible-middleware.github.io/jws
homepage: https://github.com/ansible-middleware/jws
issues: https://github.com/ansible-middleware/jws/issues
build_ignore:
  - molecule
  - .github
  - '*.tar.gz'
  - '*.zip'
  - changelogs/fragments/.gitignore
  - .gitignore
