---
namespace: middleware_automation
name: jws
version: "1.2.6"
readme: README.md
authors:
  - George Zaronikas <gzaronik@redhat.com>
  - Romain Pelisse <belaran@redhat.com>
  - Harsha Cherukuri <hcheruku@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
  - Coty Sutherland <csutherl@redhat.com>
description: This collection contains the ansible playbook to setup JWS.
license_file: "LICENSE"
tags:
  - java
  - tomcat
  - server
  - apache
  - jws
  - modcluster
  - infrastructure
  - linux
  - runtimes
  - middleware
  - a4mw
dependencies:
  middleware_automation.common: '>=1.1.0'
  ansible.posix: ">=1.4.0"
repository: https://github.com/ansible-middleware/jws
documentation: https://ansible-middleware.github.io/jws
homepage: https://github.com/ansible-middleware/jws
issues: https://github.com/ansible-middleware/jws/issues
build_ignore:
  - molecule
  - .github
  - '*.tar.gz'
  - '*.zip'
  - .gitignore
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
