---
- name: Check arguments
  assert:
    that:
      - tomcat.service.name is defined
    quiet: true

- name: "Disable tomcat service"
  service:
    name: "{{ tomcat.service.name }}"
    enabled: no

- name: "Stop tomcat service"
  include_tasks: systemd/stop.yml
