---
- name: Check if archive contains a selinux policy
  ansible.builtin.stat:
    path: "{{ jws_home }}/selinux/jws5-jws.if"
  register: archive_path_selinux

- name: "Compile and install selinux policy"
  block:
    - name: Install selinux-policy-devel
      ansible.builtin.include_tasks: ../fastpackage.yml
      vars:
        package_name: selinux-policy-devel

    - name: Check if archive contains a selinux policy
      ansible.builtin.stat:
        path: "{{ jws_home }}/selinux/jws5-jws.pp"
      register: policy_path_selinux

    - name: Create selinux policy
      ansible.builtin.command: make -f /usr/share/selinux/devel/Makefile
      args:
        chdir: "{{ jws_home }}/selinux"
        creates: "{{ jws_home }}/selinux/jws5-jws.pp"
      when:
        - not policy_path_selinux.stat.exists
      notify:
        - "Selinux policy created"
        - "Apply selinux policy"
  when: archive_path_selinux.stat.exists

- name: Allow jws.to listen to port
  community.general.seport:
    ports:
      - "{{ jws_listen_http_port }}"
      - "{{ jws_listen_https_port }}"
      - "{{ jws_listen_ajp_port }}"
      - "{{ jws_shutdown_port }}"
    proto: tcp
    setype: http_port_t
    state: present
