---
- import_playbook: playbook.yml

- name: "Red Hat JBoss Web Server uninstallation"
  hosts: all
  collections:
    - middleware_automation.jws
  post_tasks:
    - include_role:
        name: jws
        tasks_from: uninstall.yml
