---
- import_playbook: playbook.yml

- name: "Red Hat JBoss Web Server uninstallation"
  hosts: all
  post_tasks:
    - include_role:
        name: jws
        tasks_from: uninstall.yml
      vars:
        jws_service_name: tomcat
        jws_home: /opt/apache-tomcat-{{ tomcat_version }}
