---
- name: Display Ansible version
  ansible.builtin.debug:
    msg: "Ansible version is  {{ ansible_version.full }}"

- name: "Set package name for sudo"
  ansible.builtin.set_fact:
    sudo_pkg_name: 'sudo'

- name: "Ensure {{ sudo_pkg_name }} is installed (if user is root)."
  ansible.builtin.yum:
    name: "{{ sudo_pkg_name }}"
  when:
    - ansible_user_id == 'root'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "Check if {{ sudo_pkg_name }} is installed."
  ansible.builtin.assert:
    that:
      - sudo_pkg_name in ansible_facts.packages

- name: "Retrieve assets server from env"
  ansible.builtin.set_fact:
    assets_server: "{{ lookup('env','MIDDLEWARE_DOWNLOAD_RELEASE_SERVER_URL') }}"

- name: "Download and deploy jws zips from {{ assets_server }}"
  ansible.builtin.get_url:
    url: "{{ asset }}"
    dest: "{{ lookup('env', 'PWD') | default('/opt') }}"
    validate_certs: no
  delegate_to: localhost
  loop: "{{ jws_molecule_assets }}"
  loop_control:
    loop_var: asset
  when:
    - assets_server is defined
    - assets_server | length > 0
