---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  vars:
    tomcat_setup: true

    # Use Case 3 - Using JWS, installed from zipfiles, provided in the playbook path or downloaded from RHN (JWS)
    # downloading requires credentials for RHN to be defined: rhn_username and rhn_password
    jws_version: 5.6.0
    tomcat_install_method: rhn_zipfiles
    tomcat_vault_enable: True
    tomcat_vault_properties: '/opt/vault.properties'
    tomcat_vault_name: '/opt/vault.keystore'
    tomcat_vault_data: '/opt/VAULT.dat'

    # Activate extra features
    # A) install java using RPM:
    tomcat_java_version: 1.8.0
    tomcat_listen_http_bind_address: 127.0.0.1
    # B) uncomment to also start tomcat as a service under Systemd
    tomcat_systemd_enabled: True
    tomcat_service_name: tomcat
    tomcat_service_systemd_type: forking

    # workaround issue on Github actions
    ansible_distribution: 'RedHat'
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
    - jws
