---
- name: Prepare
  hosts: all
  tasks:

    - name: Display Ansible version
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: Install sudo
      ansible.builtin.yum:
        name: sudo
        state: present
