---
- name: Verify
  hosts: instance
  vars:
    jws_version: 5.6.0
    tomcat_version: False
    tomcat_vault_enable: True
  tasks:
    - name: "Deploy tomcat-vault test webapp"
      copy:
        src: "{{ item }}"
        dest: "{{ tomcat.home }}/webapps/"
      loop:
        - testapp
    - name: "Check tomcat-vault configuration"
      uri:
        url: http://localhost:8080/testapp/
        return_content: yes
      register: this
      failed_when: "'test_attr_value' not in this.content"
      retries: 3
      delay: 5
    - include_role:
        name: jws_validation
      vars:
        tomcat_catalina_logfile: /opt/jws-5.6/tomcat/logs/catalina.out
