---
- name: Read the content of catalina.out
  ansible.builtin.slurp:
    src: "{{ jws_home }}/{{ catalina_logfile }}"
  register: catalina_out

- name: Print the content of catalina.out
  ansible.builtin.debug:
    msg: "{{ catalina_out['content'] | b64decode | length }}"

- name: Fail if logfile contains ERRORs
  ansible.builtin.assert:
    that:
      - "{{ 'SEVERE' not in catalina_out.content }}"
    quiet: true
    fail_msg: "Catalina logfile contains SEVERE error lines."

- name: Fail if native is installed but fails to start
  ansible.builtin.assert:
    that:
      - "{{ 'Loaded Apache Tomcat Native library' in catalina_out.content | b64decode }}"
    quiet: true
    fail_msg: "Tomcat native extensions failed to load."
  when: jws_native
