---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Check if service is started
  ansible.builtin.assert:
    that:
      - ansible_facts is defined
      - ansible_facts.services is defined
      - ansible_facts.services["{{ jws_service_name }}.service"] is defined
      - ansible_facts.services["{{ jws_service_name }}.service"]['state'] is defined
      - ansible_facts.services["{{ jws_service_name }}.service"]['state'] == 'running'
      - ansible_facts.services["{{ jws_service_name }}.service"]['status'] == 'enabled'
    quiet: true
    fail_msg: "Service is not started."
