---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Check if service is started and print logs otherwise
  block:
    - name: Check if service is started
      ansible.builtin.assert:
        that:
          - ansible_facts is defined
          - ansible_facts.services is defined
          - ansible_facts.services["{{ jws_service_name }}.service"] is defined
          - ansible_facts.services["{{ jws_service_name }}.service"]['state'] is defined
          - ansible_facts.services["{{ jws_service_name }}.service"]['state'] == 'running'
          - ansible_facts.services["{{ jws_service_name }}.service"]['status'] == 'enabled'
        quiet: true
        fail_msg: "Service is not started."
  rescue:
    - name: Read the content of systemd logs
      ansible.builtin.command: journalctl -xe -u{{ jws_service_name }}.service --no-pager -n 50
