---
- name: Prepare
  hosts: all
  tasks:

    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../common_prepare.yml
      vars:
        jws_molecule_assets:
          - "{{ assets_server }}/webserver/5.6.0/jws-5.6.0-application-server.zip"

    - name: "Deploy https certificate"
      become: "{{ jws_install_requires_become | default(true) }}"
      ansible.builtin.copy:
        src: ./resources/keystore.jks
        dest: /etc/ssl/
        mode: 0644
        owner: root
        group: root
