---
- name: Prepare
  hosts: all
  tasks:

    - name: Display Ansible version
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Deploy https certificate"
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/
      loop:
        - ./resources/keystore.jks
