---
- name: Verify
  hosts: all
  collections:
    - middleware_automation.jws
  vars_files:
    - vars.yml
  vars:
    jws_listen_https_port: 8443
    jws_listen_https_bind_address: localhost
    # ajp config will not work with tomcat and produce errors in catalina.out
    jws_validation_allow_errors_in_catalina_log: True
  roles:
    - jws_validation
