---
- name: "Set defaults based on jws_version (if provided)."
  when:
    - jws_version is defined
  block:
    - name: Set filename for JWS zipfile
      ansible.builtin.set_fact:
        zipfile_name: "{{ jws_bundle }}"
      when:
        - not zipfile_name is defined

    - name: "Set native zipfile architecture (if not provided)"
      ansible.builtin.set_fact:
        jws_native_zipfile_arch: "{{ ansible_architecture | default('x86_64') }}"
      when:
        - not jws_native_zipfile_arch is defined

    - name: "Set RHEL major version based on facts (if not provided)."
      ansible.builtin.set_fact:
        jws_native_rhel_major_version: "{{ jws_native_rhel_version | default(ansible_facts['distribution_major_version'] | default('8')) }}"
      when:
        - not jws_native_rhel_major_version is defined

    - name: Set filename for JWS native zipfile
      ansible.builtin.set_fact:
        jws_native_zipfile: "jws-{{ jws_version }}{{ (jws_version.startswith('6') | ternary('-optional-native-components-RHEL', '-application-server-RHEL')) }}{{ jws_native_rhel_major_version }}-{{ jws_native_zipfile_arch }}.zip"
      when:
        - jws_native is defined
        - not jws_native_zipfile is defined or jws_native_zipfile | length == 0
