---
- name: Check arguments
  assert:
    that:
      - tomcat.rpm is defined
      - tomcat.rpm != ""
    quiet: true
    fail_msg: "No RPM package name provided."

- assert:
    that:
      - ansible_os_family == "RedHat"
    quiet: true
    fail_msg: "RPM install can only work on RedHat based distribution."
  when:
    - ansible_os_family is defined

- assert:
    that:
      - tomcat.home is defined
      - tomcat.home == "/opt/rh/jws5/root/usr/share/tomcat/"
    quiet: true
    fail_msg: "{{ tomcat.service.hr_name }} HOME does not match the one provided by RPM."

- name: "Install {{ tomcat.rpm }}"
  command:
    cmd: "dnf groupinstall -y {{ tomcat.rpm }}"
    creates: "{{ tomcat_rpm_root_dir }}/enable"
  notify:
    - Ensure Tomcat runs under systemd
