---
- name: Check arguments
  assert:
    that:
      - tomcat.rpm is defined
      - tomcat.rpm != ""
    quiet: true
    fail_msg: "No RPM package name provided."

- debug:
    var: dnf_command

- assert:
    that:
      - ansible_os_family == "RedHat"
    quiet: true
    fail_msg: "RPM install can only work on RedHat based distribution."
  when:
    - ansible_os_family is defined

- assert:
    that:
      - tomcat.home is defined
      - tomcat.home == "/opt/rh/jws5/root/usr/share/tomcat/"
    quiet: true
    fail_msg: "{{ tomcat.service.hr_name }} HOME does not match the one provided by RPM."

- set_fact:
    dnf_command: "'groupinstall'"
    info_msg: "Install {{ tomcat.rpm }}"
  when:
    - not dnf_command is defined

- set_fact:
    info_msg: "Remove {{ tomcat.rpm }}"
  when:
    - dnf_command is defined
    - dnf_command != "groupinstall"

- name: "{{ info_msg }}"
  command:
    cmd: "dnf {{ dnf_command | default('groupinstall') }} -y {{ tomcat.rpm }}"
    creates: "{{ tomcat_rpm_root_dir }}/enable"
  notify:
    - Ensure Tomcat runs under systemd
