---
- name: Check arguments
  assert:
    that:
      - tomcat.rpm is defined
      - tomcat.rpm != ""
    quiet: true
    fail_msg: "No RPM package name provided."

- assert:
    that:
      - ansible_os_family == "RedHat"
    quiet: true
    fail_msg: "RPM install can only work on RedHat based distribution."
  when:
    - ansible_os_family is defined

- assert:
    that:
      - tomcat.home is defined
      - tomcat.home == "/opt/rh/jws5/root/usr/share/tomcat/"
    quiet: true
    fail_msg: "Tomcat HOME does not match the one provided by RPM."

- name: "Install {{ tomcat.rpm }}"
  command:
    cmd: "yum group install -y {{ tomcat.rpm }}"
    creates: "{{ tomcat.home }}"
  notify:
    - Ensures Tomcat runs under systemd
