---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - tomcat.rpm is defined
      - tomcat.rpm != ""
    quiet: true
    fail_msg: "No RPM package name provided."

- ansible.builtin.debug:
    var: dnf_command

- name: "Verify distribution"
  ansible.builtin.assert:
    that:
      - ansible_os_family == "RedHat"
    quiet: true
    fail_msg: "RPM install can only work on RedHat based distribution."
  when:
    - ansible_os_family is defined

- name: "Verify tomcat home"
  ansible.builtin.assert:
    that:
      - tomcat.home is defined
      - tomcat.home == "/opt/rh/jws5/root/usr/share/tomcat/"
    quiet: true
    fail_msg: "{{ tomcat.service.hr_name }} HOME does not match the one provided by RPM."

- ansible.builtin.set_fact:
    dnf_command: "'groupinstall'"
    info_msg: "install {{ tomcat.rpm }}"
  when:
    - not dnf_command is defined

- ansible.builtin.set_fact:
    info_msg: "remove {{ tomcat.rpm }}"
  when:
    - dnf_command is defined
    - dnf_command != "'groupinstall'"

- name: "Perform {{ info_msg }}"
  ansible.builtin.command:
    cmd: "dnf {{ dnf_command | default('groupinstall') }} -y {{ tomcat.rpm }}"
    creates: "{{ tomcat_rpm_root_dir }}/enable"
  notify:
    - Ensure Tomcat runs under systemd
