---
- name: Download archive from custom url
  ansible.builtin.get_url:
    url: "{{ zipfile_url }}"
    dest: "{{ jws_install_dir }}/{{ zipfile_name }}"
    username: "{{ zipfile_url_username | default(omit) }}"
    password: "{{ zipfile_url_password | default(omit) }}"
    mode: 0640
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
