---
- name: "Install with override server.xml"
  hosts: all
  vars:
    # following value set the jvmRoute attribute (specific to override template)
    jvm_route: jvm_route_1
    jws_apply_patches: False
    jws_selinux_enabled: False
  vars_files:
    - ../../playbooks/vars.yml
  collections:
    - middleware_automation.jws
  roles:
    - role: jws
      jws_home: /opt/custom
      jws_conf_templates_server: override_server_xml_template.xml.j2
      jws_listen_ajp_enabled: False
      jws_systemd_enabled: True
      jws_service_systemd_type: forking
      jws_native: False
