---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  become: true
  vars_files:
    - ../../playbooks/vars.yml
  collections:
    - middleware_automation.jws
  roles:
    - jws
