---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  become: "{{ jws_install_requires_become | default(true) }}"
  vars_files:
    - ../../playbooks/vars.yml
  collections:
    - middleware_automation.jws
  roles:
    - role: jws
