---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: collections.yml
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   flake8
#   ansible-lint --force-color
platforms:
  - name: instance
    image: docker.io/centos:8
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  env:
    CATALINA_HOME: "/opt/apache-tomcat-9.0.50"
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
