---
- name: "Import RHEL 8 Python Bootstrap"
  ansible.builtin.import_playbook: ../common_bootstrap_rhel8.yml

- name: "Prepare"
  hosts: all
  gather_facts: true
  tasks:

    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../common_prepare.yml
      vars:
        jws_molecule_assets:
          - "{{ assets_server }}/webserver/5.6.0/jws-5.6.0-application-server.zip"
