---
- name: "newer version installation / jdk 11 update"
  hosts: all
  collections:
    - middleware_automation.jws
  roles:
    - role: jws
      jws_setup: true
      jws_listen_http_bind_address: 127.0.0.1
      jws_systemd_enabled: True
      jws_service_systemd_type: forking
      jws_force_install: true
      jws_java_version: 11
