---
- name: "tomcat 9.0.65 / jdk 11 update"
  hosts: all
  collections:
    - middleware_automation.jws
  pre_tasks:
    - name: "Set JWS version if resource available"
      ansible.builtin.set_fact:
        jws_version: "5.6.0"
      when: "'/opt/webserver/5.6.0/jws-5.6.0-application-server.zip' is exists"
  roles:
    - role: jws
      jws_setup: true
      jws_listen_http_bind_address: 127.0.0.1
      jws_systemd_enabled: True
      jws_service_systemd_type: forking
      jws_force_install: true
      jws_java_version: 11
