---
- name: "Prepare"
  hosts: all
  tasks:

    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../common_prepare.yml
      vars:
        jws_molecule_assets:
          - "{{ assets_server }}/webserver/5.5.0/jws-5.5.0-application-server.zip"
          - "{{ assets_server }}/webserver/5.7.0/jws-5.7.0-application-server.zip"

- name: "Older version installation"
  hosts: all
  vars_files:
    - ../../playbooks/vars.yml
  collections:
    - middleware_automation.jws
  pre_tasks:
    - name: "Set JWS version if resource available"
      ansible.builtin.set_fact:
        jws_version: 5.5.0
      when:
        - "(lookup('env', 'PWD') | default('/opt') + '/jws-5.5.0-application-server.zip') is exists"
        - jws_version is defined
  roles:
    - role: jws
      tomcat_version: 9.0.80
