---
- name: "Import RHEL 8 Python Bootstrap"
  ansible.builtin.import_playbook: ../common_bootstrap_rhel8.yml

- name: Prepare
  hosts: all
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../common_prepare.yml
      vars:
        jws_molecule_assets:
          - "{{ assets_server }}/webserver/6.0.0/jws-6.0.0-application-server.zip"
          - "{{ assets_server }}/webserver/6.1.0/jws-6.1.0-application-server.zip"

- name: "Older version installation"
  hosts: all
  vars:
    jws_apply_patches: False
    tomcat_version: 10.1.13
  vars_files:
    - ../../playbooks/vars.yml
  pre_tasks:
    - name: "Set JWS version if resource available"
      ansible.builtin.set_fact:
        jws_version: 6.0.0
      when:
        - "(lookup('env', 'PWD') | default('/opt') + '/jws-6.0.0-application-server.zip') is exists"
        - jws_version is defined
  collections:
    - middleware_automation.jws
  roles:
    - role: jws
      jws_native: False
