---
- name: Verify
  hosts: instance
  vars:
    jws_apply_patches: False
    jws_java_version: 11
    jws_native: False
    jws_selinux_enabled: False
  collections:
    - middleware_automation.jws
  roles:
    - role: jws_validation
  pre_tasks:
    - name: "Set JWS version if resource available"
      ansible.builtin.set_fact:
        jws_version: 5.7.0
      when:
        - "(lookup('env', 'PWD') | default('/opt') + '/jws-5.7.0-application-server.zip') is exists"
        - jws_version is defined
