---
- name: Verify
  hosts: instance
  pre_tasks:
    - name: "Set JWS version if resource available"
      ansible.builtin.set_fact:
        jws_version: 5.7.0
      when:
        - "(lookup('env', 'PWD') | default('/opt') + '/jws-5.7.0-application-server.zip') is exists"
        - jws_version is defined
  roles:
    - role: middleware_automation.jws.jws_validation
      jws_java_version: 11
      jws_native: False
      jws_apply_patches: False
