---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - tomcat.rhn.username is defined
      - tomcat.rhn.password is defined
      - tomcat.install_dir is defined
    quiet: true
    fail_msg: "One or more required parameters for cumulative patch application is missing."

- name: "Set native zipfile when distribution data available"
  ansible.builtin.set_fact:
    patch_native_bundle: "jws-{{ jws.rhn_ids[jws_version].latest_cp.v | default('') }}-application-server-RHEL{{ ansible_facts['distribution_major_version'] }}-x86_64.zip"
  when:
    - jws_version is defined
    - ansible_facts is defined
    - ansible_facts['distribution_major_version'] is defined

- name: "Set native zipfile when distribution data unavailable"
  ansible.builtin.set_fact:
    patch_native_bundle: "{{ jws_patch_native_bundle | default(tomcat.rhn.patch_native_bundle) }}"
  when:
    - jws_version is defined
    - not ansible_facts is defined or not ansible_facts['distribution_major_version'] is defined

- name: Check local download archive path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost

- name: Check downloaded archive
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ jws_patch_bundle | default(tomcat.rhn.patch_bundle) }}"
  register: local_archive_path
  delegate_to: localhost

- name: Check downloaded native archive
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ patch_native_bundle }}"
  register: local_native_archive_path
  delegate_to: localhost

# check remote patch archive
- name: Set download patch archive path
  ansible.builtin.set_fact:
    patch_archive: "{{ tomcat.install_dir }}/{{ tomcat.rhn.patch_bundle }}"
    patch_native_archive: "{{ tomcat.install_dir }}/{{ patch_native_bundle }}"

- name: Check download patch archive path
  ansible.builtin.stat:
    path: "{{ patch_archive }}"
  register: patch_archive_path

- name: Check download patch archive path
  ansible.builtin.stat:
    path: "{{ patch_native_archive }}"
  register: patch_native_archive_path

- name: Perform patch download from RHN
  middleware_automation.redhat_csp_download.redhat_csp_download:
    url: "{{ tomcat.rhn.cpatch_zipfile_url }}"
    dest: "{{ local_path.stat.path }}/{{ tomcat.rhn.patch_bundle }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  no_log: "{{ omit_rhn_output | default(true) }}"
  delegate_to: localhost
  when:
    - patch_archive_path is defined
    - patch_archive_path.stat is defined
    - not patch_archive_path.stat.exists
    - not local_archive_path.stat.exists

- name: Perform native patch download from RHN
  middleware_automation.redhat_csp_download.redhat_csp_download:
    url: "{{ tomcat.rhn.cpatch_native_zipfile_url }}"
    dest: "{{ local_path.stat.path }}/{{ patch_native_bundle }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  no_log: "{{ omit_rhn_output | default(true) }}"
  delegate_to: localhost
  when:
    - patch_native_archive_path is defined
    - patch_native_archive_path.stat is defined
    - not patch_native_archive_path.stat.exists
    - not local_native_archive_path.stat.exists

## copy and unpack
- name: Copy patch archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ tomcat.rhn.patch_bundle }}"
    dest: "{{ patch_archive }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0640
  register: new_version_downloaded
  when:
    - not patch_archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes

## copy and unpack
- name: Copy patch archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ patch_native_bundle }}"
    dest: "{{ patch_native_archive }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0640
  register: new_version_downloaded_native
  when:
    - not patch_native_archive_path.stat.exists
    - local_native_archive_path.stat is defined
    - local_native_archive_path.stat.exists
  become: yes

- name: "Check patch state"
  ansible.builtin.stat:
    path: "{{ patch_archive }}"
  register: patch_info

- name: "Set patch checksum"
  ansible.builtin.set_fact:
    patch_checksum_file: "{{ tomcat.home }}/../.applied_patch_checksum_{{ patch_info.stat.checksum }}.txt"
  when:
    - patch_info is defined

- name: "Check {{ patch_checksum_file }} state"
  ansible.builtin.stat:
    path: "{{ patch_checksum_file }}"
  register: last_patch_status

- name: Print when patch has been applied already
  ansible.builtin.debug:
    msg: "Patch v{{ jws.rhn_ids[jws_version].latest_cp.v }} (checksum {{ patch_info.stat.checksum }}) has already been applied."
  when:
    - last_patch_status.stat.exists

- name: "Apply JWS patch"
  block:
    - name: "Update {{ tomcat.home }} with downloaded Cumulative Patch"
      ansible.builtin.unarchive:
        src: "{{ patch_archive }}"
        dest: "{{ tomcat.install_dir }}"
        remote_src: yes
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
      notify:
        - Restart Tomcat service
      when:
        - not last_patch_status.stat.exists

    - name: "Update {{ tomcat.home }} with downloaded native Cumulative Patch"
      ansible.builtin.unarchive:
        src: "{{ patch_native_archive }}"
        dest: "{{ tomcat.install_dir }}"
        remote_src: yes
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
      notify:
        - Restart Tomcat service
      when:
        - not last_patch_status.stat.exists

    - name: Set checksum file
      ansible.builtin.copy:
        dest: "{{ patch_checksum_file }}"
        content: "Patch v{{ jws.rhn_ids[jws_version].latest_cp.v }}"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0640
      when:
        - not last_patch_status.stat.exists
  when:
    - patch_archive_path is defined
    - patch_archive_path.stat is defined
    - last_patch_status is defined
    - last_patch_status.stat is defined
  rescue:
    - ansible.builtin.debug:
        msg: "This should NEVER happen, something is wrong."
