---
# The following is only for upstream: if jws_version is not defined
# we use the latest version of Apache Tomcat
- name: "Set defaults values (if jws_version is not provided)"
  ansible.builtin.set_fact:
    zipfile_name: "apache-tomcat-{{ tomcat_version }}.zip"
  when:
    - not jws_version is defined

- name: "Set defaults values (if jws_version is not provided)"
  ansible.builtin.set_fact:
    zipfile_url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/{{ zipfile_name }}"
    jws_home: "/opt/apache-tomcat-{{ tomcat_version }}/"
  when:
    - not jws_version is defined

- name: "Set jws_home if not already defined."
  ansible.builtin.set_fact:
    jws_home: "{{ tomcat.install_dir }}/jws-{{ jws_version.split('.')[0] }}.{{ jws_version.split('.')[1] }}/tomcat"
  when:
    - not jws_home is defined
    - jws_version is defined

- name: "Check that jws_home has been defined."
  ansible.builtin.assert:
    that:
      - jws_home is defined
      - jws_home | length > 0

- name: "Install required dependencies"
  include_tasks: fastpackage.yml
  vars:
    package_name: "{{ item }}"
  loop:
    - zip
    - unzip
    - openssl
    - apr

- name: "Ensure tomcatjss rpm is not installed"
  ansible.builtin.dnf:
    name: tomcatjss
    state: absent

- name: "Include tasks for java jvm installation"
  ansible.builtin.include_tasks: java_install.yml
  when: jws_java_version is defined

- name: Check user/groups and whether force install needed
  block:
    - name: "Create group: {{ tomcat.group }}"
      ansible.builtin.group:
        name: "{{ tomcat.group }}"
        gid: "{{ tomcat.gid }}"
        system: yes

    - name: "Create user for tomcat: {{ tomcat.user }}"
      ansible.builtin.user:
        name: "{{ tomcat.user }}"
        uid: "{{ tomcat.uid }}"
        system: yes
        groups: "{{ tomcat.group }}"
        home: "{{ jws_home }}"
        shell: /sbin/nologin
        comment: "User for Apache Tomcat"
  rescue:
    - name: "Inform of process owned by {{ tomcat.user }} already running"
      ansible.builtin.assert:
        that:
          - jws_force_install
        fail_msg: "Found a process owned by {{ tomcat.user }} and jws_force_install is false, aborting installation"
        success_msg: "Found a process owned by {{ tomcat.user }} and jws_force_install is true, continuing installation anyway"

    - name: "Include force install steps"
      include_tasks: install/force_install.yml
      when: jws_force_install

- name: Perform setup
  block:
    - name: "Check state of install_dir: {{ jws_install_dir }}"
      ansible.builtin.stat:
        path: "{{ jws_install_dir }}"
      register: install_path

    - name: "Ensure install dir is created: {{ jws_install_dir }}"
      ansible.builtin.file:
        path: "{{ jws_install_dir }}"
        state: directory
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
      when:
        - not install_path.stat.exists
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"

    - name: "Include install tasks"
      ansible.builtin.include_tasks: install.yml
      when:
        - tomcat.install_method is defined

    - name: "Include systemd tasks"
      ansible.builtin.include_tasks: systemd/systemd.yml
      when:
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"
        - tomcat.service is defined
        - tomcat.service.enabled is defined
        - tomcat.service.enabled

    - name: Include patch install tasks
      ansible.builtin.include_tasks: apply_cp.yml
      when:
        - jws_apply_patches
        - tomcat.install_method == "rhn_zipfiles"
        - jws.rhn_ids[jws_version].latest_cp is defined
        - jws.rhn_ids[jws_version].latest_cp.id is defined
        - jws.rhn_ids[jws_version].latest_cp.v is defined

    - name: "Ensure {{ jws_home }}/ directories have appropriate privileges"
      ansible.builtin.file:
        path: "{{ jws_home }}/{{ item }}/"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
        state: directory
      loop:
        - conf
        - temp
        - logs
        - webapps
        - bin

    - name: "Ensure {{ jws_home }}/ files have the recommended priviliges, owner and group"
      ansible.builtin.file:
        path: "{{ jws_home }}/{{ item }}"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0600
      loop:
        - "{{ tomcat.conf.properties }}"
        - "{{ tomcat.conf.policy }}"
        - "{{ tomcat.conf.logging }}"
        - "conf/tomcat-users.xml"
        - "conf/jaspic-providers.xml"

    - name: "Include ajp sanity check tasks"
      ansible.builtin.include_tasks: sanity_checks/ajp.yml
      when:
        - tomcat.listen.ajp.enabled is defined
        - jws_listen_ajp_enabled

    - name: "Include https sanity check tasks"
      ansible.builtin.include_tasks: sanity_checks/https.yml
      when:
        - jws_listen_https_enabled is defined
        - jws_listen_https_enabled

    - name: "Deploy custom configuration files"
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ item.dest }}"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0600
      loop:
        - { template: "{{ tomcat.conf.templates.server }}", dest: "{{ jws_home }}/{{ tomcat.conf.server }}" }
        - { template: "{{ tomcat.conf.templates.web }}", dest: "{{ jws_home }}/{{ tomcat.conf.web }}" }
        - { template: "{{ tomcat.conf.templates.context }}", dest: "{{ jws_home }}/{{ tomcat.conf.context }}" }
        - { template: "{{ tomcat.conf.templates.catalina_properties }}", dest: "{{ jws_home }}/{{ tomcat.conf.properties }}" }
      notify:
        - Restart Tomcat service

    - name: "Include selinux configuration tasks"
      ansible.builtin.include_tasks: systemd/selinux.yml
      when:
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"
        - jws_selinux_enabled and tomcat.install_method == "rhn_zipfiles"

    - name: "Remove apps"
      ansible.builtin.file:
        path: "{{ jws_home }}/webapps/{{ item }}"
        state: absent
      loop: "{{ tomcat.apps.to_remove }}"
      when: tomcat.apps.to_remove is defined

    - name: "Create vault configuration"
      block:
        - name: "Copy {{ tomcat.service.hr_name }} vault keystore from control node to remote"
          ansible.builtin.copy:
            src: "{{ tomcat.vault.name }}"
            dest: "{{ jws_home }}"
            owner: "{{ tomcat.user }}"
            group: "{{ tomcat.group }}"
            mode: 0640

        - name: "Copy {{ tomcat.service.hr_name }} vault properties file from control node to remote"
          ansible.builtin.copy:
            src: "{{ tomcat.vault.properties }}"
            dest: "{{ jws_home }}/conf/"
            owner: "{{ tomcat.user }}"
            group: "{{ tomcat.group }}"
            mode: 0640

        - name: "Copy {{ tomcat.service.hr_name }} vault data file from control node to remote"
          ansible.builtin.copy:
            src: "{{ tomcat.vault.data }}"
            dest: "{{ jws_home }}"
            owner: "{{ tomcat.user }}"
            group: "{{ tomcat.group }}"
            mode: 0640

      when: tomcat.vault.enable
  when: jws_setup
