---
- name: "Check that tomcat.home has been defined."
  assert:
    that:
      - tomcat.home is defined
      - tomcat.home | length > 0

- name: "Install required dependencies"
  include_tasks: fastpackage.yml
  vars:
    package_name: "{{ item }}"
  loop:
    - zip
    - unzip

- include_tasks: java_install.yml
  when: tomcat_java_version is defined

- block:
    - name: "Create group: {{ tomcat.group }}"
      group:
        name: "{{ tomcat.group }}"
        gid: "{{ tomcat.gid }}"
        system: yes

    - name: "Create user for tomcat: {{ tomcat.user }}"
      user:
        name: "{{ tomcat.user }}"
        uid: "{{ tomcat.uid }}"
        system: yes
        groups: "{{ tomcat.group }}"
        home: "{{ tomcat.home }}"
        shell: /sbin/nologin
        comment: "User for Apache Tomcat"
  rescue:
    - name: "Inform of process owned by {{ tomcat.user }} already running"
      assert:
        that:
          - tomcat_force_install
        fail_msg: "Found a process owned by {{ tomcat.user }} and tomcat_force_install is false, aborting installation"
        success_msg: "Found a process owned by {{ tomcat.user }} and tomcat_force_install is true, continuing installation anyway"

    - name: "Include force install steps"
      include_tasks: install/force_install.yml
      when: tomcat_force_install

- block:
    - name: "Ensure install dir is created: {{ tomcat_install_dir }}"
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
      when:
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"

    - include_tasks: install.yml
      when:
        - tomcat.install_method is defined

    - include_tasks: systemd/systemd.yml
      when:
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"
        - tomcat.service is defined
        - tomcat.service.enabled is defined
        - tomcat.service.enabled

    - name: Include patch install tasks
      ansible.builtin.include_tasks: apply_cp.yml
      when: jws_apply_patches and tomcat.install_method == "rhn_zipfiles"

    - name: "Ensure {{ tomcat.home }}/ directories have appropriate privileges"
      file:
        path: "{{ tomcat.home }}/{{ item }}/"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0750
        state: directory
      loop:
        - conf
        - temp
        - logs
        - webapps
        - bin

    - name: "Ensure {{ tomcat.home }}/ files have the recommended priviliges, owner and group"
      file:
        path: "{{ tomcat.home }}/{{ item }}"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0600
      loop:
        - "{{ tomcat.conf.properties }}"
        - "{{ tomcat.conf.policy }}"
        - "{{ tomcat.conf.logging }}"
        - "conf/tomcat-users.xml"
        - "conf/jaspic-providers.xml"

    - include_tasks: sanity_checks/ajp.yml
      when:
        - tomcat.listen.ajp.enabled is defined
        - tomcat_listen_ajp_enabled

    - include_tasks: sanity_checks/https.yml
      when:
        - tomcat_listen_https_enabled is defined
        - tomcat_listen_https_enabled

    - name: "Deploy custom configuration files"
      template:
        src: "{{ item.template }}"
        dest: "{{ item.dest }}"
        owner: "{{ tomcat.user }}"
        group: "{{ tomcat.group }}"
        mode: 0600
      loop:
        - { template: "{{ tomcat.conf.templates.server }}", dest: "{{ tomcat.home }}/{{ tomcat.conf.server }}" }
        - { template: "{{ tomcat.conf.templates.web }}", dest: "{{ tomcat.home }}/{{ tomcat.conf.web }}" }
        - { template: "{{ tomcat.conf.templates.context }}", dest: "{{ tomcat.home }}/{{ tomcat.conf.context }}" }
      notify:
        - Restart Tomcat service

    - include_tasks: systemd/selinux.yml
      when:
        - tomcat.install_method is defined
        - tomcat.install_method != "rpm"

    - name: "Remove apps"
      file:
        path: "{{ tomcat.home }}/webapps/{{ item }}"
        state: absent
      loop: "{{ tomcat.apps.to_remove }}"
      when: tomcat.apps.to_remove is defined

    - block:
        - name: "Copy {{ tomcat.service.hr_name }} vault file from control node to remote"
          copy:
            src: "{{ tomcat.vault.name }}"
            dest: "{{ tomcat.home }}/"
            owner: "{{ tomcat.user }}"
            group: "{{ tomcat.group }}"
            mode: 0750

        - name: "Initialize {{ tomcat.service.hr_name }} vault"
          command:
            cmd: "{{ tomcat.home }}/bin/tomcat-vault.sh --keystore {{ tomcat.home }}/vault.keystore --keystore-password {{ tomcat.vault.storepass }} --alias {{ tomcat.vault.alias }} --enc-dir {{ tomcat.home }} --iteration {{ tomcat.vault.iteration }} --salt {{ tomcat.vault.salt }} -g {{ tomcat.home }}/{{ tomcat.vault.properties }}"
      when: tomcat.vault.enable
  when: tomcat_setup
