---
name: Documentation
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  docs:
    uses: ansible-middleware/github-actions/.github/workflows/docs.yml@main
    secrets: inherit
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      packages: write
      pages: write
    with:
      fqcn: 'middleware_automation/jws'
      collection_fqcn: 'middleware_automation.jws'
