---
name: Documentation
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  docs:
    if: ${{ github.repository == 'ansible-middleware/jws' }}
    uses: ansible-middleware/github-actions/.github/workflows/docs.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/jws'
      collection_fqcn: 'middleware_automation.jws'
