name: Collect traffic stats
on:
  schedule: 
    - cron: "51 23 * * 0"
  workflow_dispatch: 
    
jobs:
  traffic:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ansible-middleware/jws' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"
    
      - name: GitHub traffic 
        uses: sangonzal/repository-traffic-action@v.0.1.6
        env:
          TRAFFIC_ACTION_TOKEN: ${{ secrets.TRIGGERING_PAT }} 
     
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Ansible Middleware
          message: "GitHub traffic"
          add: "./traffic/*"
          ref: "gh-pages"
